server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


  jpa:
   hibernate:
     ddl-auto: update
   show-sql: true
   properties:
     hibernate:
       dialect: org.hibernate.dialect.MySQL8Dialect
       globally_quoted_identifiers: true
       format_sql: true
  application:
    name: USER-SERVICE
#  cloud:
#    config:
#      import: http://localhost:8088

#welcome:
#  message: "inside local yml"


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      user_rating_circuitBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  ratelimiter:
    instances:
      nameOfRateLimiter:
        limit-refresh-period: 5s
        limit-for-period: 2
        timeout-duration: 0s


